flags = -Wall -Werror -Wextra -g -c -std=c99
conjuntos = ../Conjuntos/conjuntos.h
hashavl = ../HashAVL/hashavl.h

interprete.o: interprete.c interprete.h $(hashavl) $(conjuntos)
	gcc $(flags) interprete.c

